# Generated by Django 5.0.2 on 2024-03-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_desc', models.CharField(max_length=255)),
                ('display_img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('full_desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
