version: '3.8'
services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env 
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend: 
    build: 
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - '80:80'
    depends_on:
      - api

volumes:
  db_data: