version: '3.8'
services:
  # certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - frontend
    env_file:
      - .env
    entrypoint: ./certbot_entrypoint.sh
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
  # django
  api: 
    container_name: api
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - '8000:8000'
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --keyfile /etc/letsencrypt/live/bryankristofferson.com/privkey.pem --certfile /etc/letsencrypt/live/bryankristofferson.com/fullchain.pem"
    depends_on:
      - db
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  # postgres
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env 
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # react/nginx
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - api
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

volumes:
  db_data:
