version: '3.8'
services:
# django
  api: 
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - '8000:8000'
    command: >
      sh -c " python manage.py migrate &&
          gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
  # postgres
  db:
    image: postgres:latest
    env_file:
      - .env 
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # react/nginx
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - api
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"

volumes:
  db_data:
